#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
    app = len(apples)
    aple = []
    ora = len(oranges)
    orang = []
    sam_apple = 0
    sam_orange = 0
    aa = 0
    bb = 0
    for aa in range(len(apples)):
        aple.append(a + apples[aa])
        if aple[aa] >= s and aple[aa] <= t:
            sam_apple += 1
    for bb in range(len(oranges)):
        orang.append(b + oranges[bb])
        if orang[bb] >= s and orang[bb] <= t:
            sam_orange += 1
    print(sam_apple)
    print(sam_orange)
    
if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
