#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    x = 0
    h = 0
    l = 0
    g = 0
    lp = []
    high = scores[0]
    luck = sorted(list(set(scores)))
    low = scores[0]
    for x in range(len(scores)):
        if scores[x] > high:
            high = scores[x]
            h += 1
        elif scores[x] < low:
            low = scores[x]
            l += 1
                  
    return (h,l)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
