#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    sums = 0
    je = []
    x = 0
    y = 0
    b = 0
    for x in range(len(arr)):
        b = arr[x]
        arr[x] = 0
        for y in range(len(arr)):
            sums += arr[y]
        je.append(sums)
        sums = 0
        arr[x] = b
    print(min(je),max(je))
if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
