#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    positif = 0
    negative = 0
    zero = 0
    s = len(arr)
    for x in range(len(arr)):
        if arr[x] > 0:
            positif += 1
        elif arr[x] < 0:
            negative +=1
        elif arr[x] == 0:
            zero += 1
    value1 = positif / s
    value2 = negative / s
    value3 = zero / s
    print(value1)
    print(value2)
    print(value3)
if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
