#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    z = 0
    b = n - 1
    for x in range(1,n+1):
        spasi = " " * b
        b = b - 1
        pagar = "#" * x
        print(spasi + pagar)
    
if __name__ == '__main__':
    n = int(input())

    staircase(n)
